// Generated by scripts/run_evaluation.py from aggregate-only evidence.
export const evidence = {
  "period": "1 Aug - 31 Oct 2018",
  "splits": "68,002 train | 66,788 calibration | 98,364 test",
  "selectedModel": "Calibrated challenger",
  "testApplicants": 98364,
  "metrics": {
    "auroc": "0.644",
    "prAuc": "0.339",
    "brier": "0.174",
    "ece": "0.045"
  },
  "policies": [
    {
      "key": "conservative",
      "label": "Conservative",
      "threshold": "16.00%",
      "approval": "44.69%",
      "review": "28.04%",
      "defaultRate": "15.29%",
      "approvedCount": 43961,
      "reviewCount": 27585,
      "approvedAmountInr": 2276270468.0,
      "defaultedAmountInr": 357726618.0,
      "netContributionInr": -747345.54,
      "decision": "Not recommended at the published assumptions",
      "netContributionRangeInr": [
        -6498712.74,
        4942467.91
      ],
      "approvalRateRange": [
        0.44381,
        0.45021
      ],
      "defaultRateRange": [
        0.14899,
        0.15657
      ],
      "positiveShare": 0.3875
    },
    {
      "key": "reference",
      "label": "Reference",
      "threshold": "22.00%",
      "approval": "67.04%",
      "review": "16.23%",
      "defaultRate": "18.37%",
      "approvedCount": 65946,
      "reviewCount": 15968,
      "approvedAmountInr": 3565186186.0,
      "defaultedAmountInr": 675507370.0,
      "netContributionInr": -35209448.18,
      "decision": "Not recommended at the published assumptions",
      "netContributionRangeInr": [
        -42450980.0,
        -27373457.09
      ],
      "approvalRateRange": [
        0.66736,
        0.6731
      ],
      "defaultRateRange": [
        0.18033,
        0.1866
      ],
      "positiveShare": 0.0
    },
    {
      "key": "expansion",
      "label": "Expansion",
      "threshold": "28.00%",
      "approval": "85.99%",
      "review": "19.58%",
      "defaultRate": "21.08%",
      "approvedCount": 84586,
      "reviewCount": 19262,
      "approvedAmountInr": 4688437408.0,
      "defaultedAmountInr": 1022267547.0,
      "netContributionInr": -130754416.59,
      "decision": "Not recommended at the published assumptions",
      "netContributionRangeInr": [
        -140958720.31,
        -121249960.04
      ],
      "approvalRateRange": [
        0.85777,
        0.86219
      ],
      "defaultRateRange": [
        0.20784,
        0.21374
      ],
      "positiveShare": 0.0
    }
  ],
  "assumptions": {
    "contributionRate": 0.12,
    "lossSeverity": 0.65,
    "reviewCostInr": 1500.0
  },
  "bandSeparation": {
    "best_band": "conservative",
    "runner_up": "reference",
    "intervals_overlap": false,
    "note": "95% intervals from resampling the October holdout with the cut-offs held fixed. They cover sampling variation only, not the economic assumptions."
  },
  "impactByGroup": [
    {
      "attribute": "State",
      "band": "conservative",
      "group": "1",
      "loans": 3423,
      "approval_rate": 0.6021,
      "observed_default_rate": 0.20158,
      "approval_ratio_to_best": 0.9987
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "2",
      "loans": 1760,
      "approval_rate": 0.24659,
      "observed_default_rate": 0.31761,
      "approval_ratio_to_best": 0.409
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "3",
      "loans": 17757,
      "approval_rate": 0.60286,
      "observed_default_rate": 0.19716,
      "approval_ratio_to_best": 1.0
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "4",
      "loans": 18996,
      "approval_rate": 0.42983,
      "observed_default_rate": 0.228,
      "approval_ratio_to_best": 0.713
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "5",
      "loans": 4599,
      "approval_rate": 0.5212,
      "observed_default_rate": 0.21657,
      "approval_ratio_to_best": 0.8645
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "6",
      "loans": 14383,
      "approval_rate": 0.45484,
      "observed_default_rate": 0.22096,
      "approval_ratio_to_best": 0.7545
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "7",
      "loans": 2436,
      "approval_rate": 0.4335,
      "observed_default_rate": 0.23317,
      "approval_ratio_to_best": 0.7191
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "8",
      "loans": 5382,
      "approval_rate": 0.40412,
      "observed_default_rate": 0.26644,
      "approval_ratio_to_best": 0.6703
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "9",
      "loans": 5930,
      "approval_rate": 0.41737,
      "observed_default_rate": 0.24772,
      "approval_ratio_to_best": 0.6923
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "10",
      "loans": 1315,
      "approval_rate": 0.58099,
      "observed_default_rate": 0.19163,
      "approval_ratio_to_best": 0.9637
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "11",
      "loans": 2590,
      "approval_rate": 0.40309,
      "observed_default_rate": 0.20425,
      "approval_ratio_to_best": 0.6686
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "12",
      "loans": 1625,
      "approval_rate": 0.56123,
      "observed_default_rate": 0.35077,
      "approval_ratio_to_best": 0.9309
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "13",
      "loans": 6836,
      "approval_rate": 0.10123,
      "observed_default_rate": 0.31978,
      "approval_ratio_to_best": 0.1679
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "14",
      "loans": 3440,
      "approval_rate": 0.18895,
      "observed_default_rate": 0.29041,
      "approval_ratio_to_best": 0.3134
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "15",
      "loans": 2379,
      "approval_rate": 0.52333,
      "observed_default_rate": 0.24128,
      "approval_ratio_to_best": 0.8681
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "16",
      "loans": 1150,
      "approval_rate": 0.55391,
      "observed_default_rate": 0.21043,
      "approval_ratio_to_best": 0.9188
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "17",
      "loans": 1843,
      "approval_rate": 0.46555,
      "observed_default_rate": 0.24797,
      "approval_ratio_to_best": 0.7722
    },
    {
      "attribute": "State",
      "band": "conservative",
      "group": "18",
      "loans": 1936,
      "approval_rate": 0.45919,
      "observed_default_rate": 0.23967,
      "approval_ratio_to_best": 0.7617
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "1",
      "loans": 3423,
      "approval_rate": 0.8364,
      "observed_default_rate": 0.20158,
      "approval_ratio_to_best": 0.9771
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "2",
      "loans": 1760,
      "approval_rate": 0.45341,
      "observed_default_rate": 0.31761,
      "approval_ratio_to_best": 0.5297
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "3",
      "loans": 17757,
      "approval_rate": 0.8199,
      "observed_default_rate": 0.19716,
      "approval_ratio_to_best": 0.9578
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "4",
      "loans": 18996,
      "approval_rate": 0.66761,
      "observed_default_rate": 0.228,
      "approval_ratio_to_best": 0.7799
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "5",
      "loans": 4599,
      "approval_rate": 0.75951,
      "observed_default_rate": 0.21657,
      "approval_ratio_to_best": 0.8873
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "6",
      "loans": 14383,
      "approval_rate": 0.67142,
      "observed_default_rate": 0.22096,
      "approval_ratio_to_best": 0.7844
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "7",
      "loans": 2436,
      "approval_rate": 0.70361,
      "observed_default_rate": 0.23317,
      "approval_ratio_to_best": 0.822
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "8",
      "loans": 5382,
      "approval_rate": 0.6388,
      "observed_default_rate": 0.26644,
      "approval_ratio_to_best": 0.7463
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "9",
      "loans": 5930,
      "approval_rate": 0.64503,
      "observed_default_rate": 0.24772,
      "approval_ratio_to_best": 0.7535
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "10",
      "loans": 1315,
      "approval_rate": 0.78707,
      "observed_default_rate": 0.19163,
      "approval_ratio_to_best": 0.9195
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "11",
      "loans": 2590,
      "approval_rate": 0.60463,
      "observed_default_rate": 0.20425,
      "approval_ratio_to_best": 0.7063
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "12",
      "loans": 1625,
      "approval_rate": 0.856,
      "observed_default_rate": 0.35077,
      "approval_ratio_to_best": 1.0
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "13",
      "loans": 6836,
      "approval_rate": 0.32563,
      "observed_default_rate": 0.31978,
      "approval_ratio_to_best": 0.3804
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "14",
      "loans": 3440,
      "approval_rate": 0.34273,
      "observed_default_rate": 0.29041,
      "approval_ratio_to_best": 0.4004
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "15",
      "loans": 2379,
      "approval_rate": 0.75032,
      "observed_default_rate": 0.24128,
      "approval_ratio_to_best": 0.8765
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "16",
      "loans": 1150,
      "approval_rate": 0.76522,
      "observed_default_rate": 0.21043,
      "approval_ratio_to_best": 0.8939
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "17",
      "loans": 1843,
      "approval_rate": 0.61096,
      "observed_default_rate": 0.24797,
      "approval_ratio_to_best": 0.7137
    },
    {
      "attribute": "State",
      "band": "reference",
      "group": "18",
      "loans": 1936,
      "approval_rate": 0.70093,
      "observed_default_rate": 0.23967,
      "approval_ratio_to_best": 0.8188
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "1",
      "loans": 3423,
      "approval_rate": 0.9407,
      "observed_default_rate": 0.20158,
      "approval_ratio_to_best": 0.959
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "2",
      "loans": 1760,
      "approval_rate": 0.72216,
      "observed_default_rate": 0.31761,
      "approval_ratio_to_best": 0.7362
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "3",
      "loans": 17757,
      "approval_rate": 0.94453,
      "observed_default_rate": 0.19716,
      "approval_ratio_to_best": 0.9629
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "4",
      "loans": 18996,
      "approval_rate": 0.86439,
      "observed_default_rate": 0.228,
      "approval_ratio_to_best": 0.8812
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "5",
      "loans": 4599,
      "approval_rate": 0.9065,
      "observed_default_rate": 0.21657,
      "approval_ratio_to_best": 0.9241
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "6",
      "loans": 14383,
      "approval_rate": 0.85448,
      "observed_default_rate": 0.22096,
      "approval_ratio_to_best": 0.8711
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "7",
      "loans": 2436,
      "approval_rate": 0.90066,
      "observed_default_rate": 0.23317,
      "approval_ratio_to_best": 0.9182
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "8",
      "loans": 5382,
      "approval_rate": 0.84857,
      "observed_default_rate": 0.26644,
      "approval_ratio_to_best": 0.8651
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "9",
      "loans": 5930,
      "approval_rate": 0.86678,
      "observed_default_rate": 0.24772,
      "approval_ratio_to_best": 0.8836
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "10",
      "loans": 1315,
      "approval_rate": 0.9346,
      "observed_default_rate": 0.19163,
      "approval_ratio_to_best": 0.9528
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "11",
      "loans": 2590,
      "approval_rate": 0.83668,
      "observed_default_rate": 0.20425,
      "approval_ratio_to_best": 0.853
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "12",
      "loans": 1625,
      "approval_rate": 0.98092,
      "observed_default_rate": 0.35077,
      "approval_ratio_to_best": 1.0
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "13",
      "loans": 6836,
      "approval_rate": 0.66545,
      "observed_default_rate": 0.31978,
      "approval_ratio_to_best": 0.6784
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "14",
      "loans": 3440,
      "approval_rate": 0.62791,
      "observed_default_rate": 0.29041,
      "approval_ratio_to_best": 0.6401
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "15",
      "loans": 2379,
      "approval_rate": 0.90458,
      "observed_default_rate": 0.24128,
      "approval_ratio_to_best": 0.9222
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "16",
      "loans": 1150,
      "approval_rate": 0.92348,
      "observed_default_rate": 0.21043,
      "approval_ratio_to_best": 0.9414
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "17",
      "loans": 1843,
      "approval_rate": 0.78025,
      "observed_default_rate": 0.24797,
      "approval_ratio_to_best": 0.7954
    },
    {
      "attribute": "State",
      "band": "expansion",
      "group": "18",
      "loans": 1936,
      "approval_rate": 0.89153,
      "observed_default_rate": 0.23967,
      "approval_ratio_to_best": 0.9089
    },
    {
      "attribute": "Employment",
      "band": "conservative",
      "group": "Salaried",
      "loans": 40420,
      "approval_rate": 0.4808,
      "observed_default_rate": 0.22138,
      "approval_ratio_to_best": 1.0
    },
    {
      "attribute": "Employment",
      "band": "conservative",
      "group": "Self employed",
      "loans": 54373,
      "approval_rate": 0.42409,
      "observed_default_rate": 0.2456,
      "approval_ratio_to_best": 0.882
    },
    {
      "attribute": "Employment",
      "band": "reference",
      "group": "Salaried",
      "loans": 40420,
      "approval_rate": 0.6877,
      "observed_default_rate": 0.22138,
      "approval_ratio_to_best": 1.0
    },
    {
      "attribute": "Employment",
      "band": "reference",
      "group": "Self employed",
      "loans": 54373,
      "approval_rate": 0.6588,
      "observed_default_rate": 0.2456,
      "approval_ratio_to_best": 0.958
    },
    {
      "attribute": "Employment",
      "band": "expansion",
      "group": "Salaried",
      "loans": 40420,
      "approval_rate": 0.86477,
      "observed_default_rate": 0.22138,
      "approval_ratio_to_best": 1.0
    },
    {
      "attribute": "Employment",
      "band": "expansion",
      "group": "Self employed",
      "loans": 54373,
      "approval_rate": 0.85577,
      "observed_default_rate": 0.2456,
      "approval_ratio_to_best": 0.9896
    }
  ],
  "labelCaveats": {
    "outcome": "Verified default on the first EMI on its due date.",
    "operational_contamination": "The book runs at a 21.7% first-EMI default rate, but the source cannot separate credit events from mandate or payment-plumbing failures and does not observe later cure or realized loss. Operational contamination is plausible, not measured. Any onboarding response requires lender evidence on first-presentation failure, cure, and loss.",
    "loss_severity_mismatch": "Loss severity is applied to disbursal on loans that missed the first EMI. A first-EMI miss is a delinquency flag, not a loss event, and a large share of first-payment defaulters cure. The 65% figure is an ultimate-loss assumption charged against an early-delinquency population, which overstates credit loss by an amount this dataset cannot quantify: it carries no recovery, roll-rate, or ultimate-default data.",
    "seasonality": "August trains, September calibrates, October tests: three consecutive months of one quarter, with no out-of-time validation beyond a single month and no economic cycle. October 2018 also falls in the Indian festival period, the peak of the vehicle-sales year, which draws a different applicant mix. Some of the October deterioration may be seasonal rather than a model or population problem, and nothing here separates the two.",
    "calibration_currency": "The isotonic calibrator was fitted on September and applied to October, and the months ran at different default rates, so predicted probabilities sit below observed across every decile. The scores rank; they do not price. Fit any replacement calibrator on the most recent closed month, then apply it to the next scoring period."
  },
  "calibrationDrift": {
    "calibration_month_default_rate": 0.19188,
    "test_month_default_rate": 0.23515,
    "base_rate_shift": 0.04327,
    "mean_predicted": 0.19004,
    "mean_gap": 0.04511,
    "ece_published": 0.04542,
    "ece_after_prior_shift": 0.00926,
    "share_of_error_from_base_rate": 0.7961,
    "odds_factor": 1.3304,
    "note": "The correction uses the test month's own base rate, which is not knowable in advance, so this is a diagnostic and not a deployable adjustment. It bounds what a correctly-timed recalibration could recover. Refitting the calibrator on the month being scored would not be time-safe and is not done here."
  },
  "sensitivityAxes": {
    "contributionRate": [
      0.1,
      0.12,
      0.14
    ],
    "lossSeverity": [
      0.55,
      0.65,
      0.75
    ],
    "reviewCostInr": [
      0.0,
      1500.0,
      3000.0
    ]
  }
};
